name: Build & Deploy to Firebase Hosting

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install deps
        run: npm ci --legacy-peer-deps

      - name: Replace environment variables
        run: |
          sed -i 's/PLACEHOLDER_API_KEY/${{ secrets.FIREBASE_API_KEY }}/g' src/environments/environment.ts
          sed -i 's/PLACEHOLDER_AUTH_DOMAIN/${{ secrets.FIREBASE_AUTH_DOMAIN }}/g' src/environments/environment.ts
          sed -i 's/PLACEHOLDER_PROJECT_ID/${{ secrets.FIREBASE_PROJECT_ID }}/g' src/environments/environment.ts
          sed -i 's/PLACEHOLDER_STORAGE_BUCKET/${{ secrets.FIREBASE_STORAGE_BUCKET }}/g' src/environments/environment.ts
          sed -i 's/PLACEHOLDER_MESSAGING_SENDER_ID/${{ secrets.MESSAGING_SENDER_ID }}/g' src/environments/environment.ts
          sed -i 's/PLACEHOLDER_APP_ID/${{ secrets.FIREBASE_APP_ID }}/g' src/environments/environment.ts
          sed -i 's/PLACEHOLDER_MEASUREMENT_ID/${{ secrets.FIREBASE_MEASUREMENT_ID }}/g' src/environments/environment.ts


      - name: Build Angular (prod)
        run: npm run build -- --configuration production

      # Deploy with service account (works with private repos)
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0.9.0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: 'sba-ai'
          channelId: live